### PR TITLE
Implement simple command line arguments parser

### PR DESCRIPTION
**Pull request by ibado**
For the Pull Request to be accepted please check:

- [x] The PR has a meaningful title.
- [x] If the PR refers to an issue, it should be referenced with the GitHub format (*#ID*).
- [x] The PR is done to the `develop` branch (new features) or the `master` branch (releases).
- [ ] The code pass all PR checks.
- [ ] All public members are documented using [KDoc].
- [ ] The code follow the coding conventions stated at the [contributing.md] file.

[KDoc]: https://kotlinlang.org/docs/kotlin-doc.html
[contributing.md]: https://github.com/hexagonkt/.github/blob/master/contributing.md

### CODE REVIEW

**Comment by jaguililla** [comment]
I'll be keeping an eye on the changes, and check the result when you remove the `WIP` tag. I like checking the changes as you do them... Is more convenient than having the PR at the end, thanks!

**Comment by jaguililla** [comment]
You can check how to minimize casting options to their target values on [this code](https://github.com/hexagonkt/hexagon/blob/master/core/src/main/kotlin/com/hexagonkt/core/Jvm.kt#L131).

**Comment by ibado** [comment]
Hi @jaguililla, feel free to take a look now and LMK what you think.
I know it has been a while since last updates. I've been busy :sweat_smile:

**Comment by jaguililla** [comment]
> Hi @jaguililla, feel free to take a look now and LMK what you think. I know it has been a while since last updates. I've been busy sweat_smile

I'm glad you made it 🙂... just for the record, if you want to go the extra mile, you can add the API documentation 😉.

I'll merge it as it is, if you want to contribute the docs, you can follow the pointers stated [here](https://github.com/hexagonkt/hexagon/issues/271) and file another PR.

Thank you very much for your contribution!

**Pull request merged**
