### PR TITLE
Hello world build fix in Quick Start page

### PR DESCRIPTION
**Pull request by abhishekabk5**
**REPLACE WITH PR DESCRIPTION** (It is also editable after PR creation)

---

For the Pull Request to be accepted please check:

- [ ] The PR has a meaningful title.
- [ ] If the PR refers to an issue, it should be referenced with the GitHub format (*#ID*).
- [ ] The PR is done to the `develop` branch (new features) or the `master` branch (releases).
- [ ] The code pass all PR checks.
- [ ] All public members are documented using [KDoc].
- [ ] The code follow the coding conventions stated at the [contributing.md] file.

[KDoc]: https://kotlinlang.org/docs/kotlin-doc.html
[contributing.md]: https://github.com/hexagonkt/.github/blob/master/contributing.md

### CODE REVIEW

**Comment by abhishekabk5** [comment]
Update HelloWorldTest.kt hello world docs to include missing imports.
Update quick_start.md to include a name in the endpoint, so there's no 404.

**Comment by jaguililla** [comment]
Thanks for fixing the documentation!

**Comment by jaguililla** [comment]
Coul you please roll back the changes on http/http_test/src/test/kotlin/com/hexagonkt/http/test/HelloWorldTest.kt? that file changes are only imports and make the build task fail. Thanks!

**Comment by abhishekabk5** [comment]
I'm not sure what's making the build fail, reason I moved these imports was so the they show up in the docs, and the reader has the full list of imports needed in the example.
Could you explain to me what part of the build is failing?
And if it's not easily fixable, I can maybe comment the imports, so they're still available in the docs? it would show up as weird though

**Comment by jaguililla** [comment]
Hi again, you made a good point about the imports.

The reason why the build is failing is because of the README.md samples check: https://github.com/hexagonkt/hexagon/blob/develop/site/build.gradle.kts#L95

That part of the build makes sure the examples written in the readme are the same as in the tests.

For the build workflow to pass, those imports should also be included in the readme's example: https://github.com/hexagonkt/hexagon/blob/develop/README.md?plain=1#L121

You can check that everything is ok locally by executing: `./gradlew checkDocs`

If you find any other problem, just let me know 🙂

**Comment by jaguililla** [comment]
I've merged the PR. Thanks for your contribution!

**Pull request merged**
